{"name": "测试用例描述：正确的账号密码登录成功", "status": "broken", "statusDetails": {"message": "TypeError: __call__() got multiple values for argument 'name'", "trace": "self = <testcase.test_5.Test object at 0x0000026F52DC3D30>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.story(\"登录\")\n    @allure.description('测试描述：登录成功')\n    @allure.title('测试用例描述：正确的账号密码登录成功')\n    def test_11(self):\n        with allure.step(\"输入正确的账号密码\"):\n>           allure.attach('13800138006','123456', name='正确账号,正确密码')\nE           TypeError: __call__() got multiple values for argument 'name'\n\ntest_5.py:26: TypeError"}, "description": "测试描述：登录成功", "steps": [{"name": "输入正确的账号密码", "status": "broken", "statusDetails": {"message": "TypeError: __call__() got multiple values for argument 'name'\n", "trace": "  File \"C:\\Users\\Administrator\\.jenkins\\workspace\\psimsendemail\\untitled\\testcase\\test_5.py\", line 26, in test_11\n    allure.attach('13800138006','123456', name='正确账号,正确密码')\n"}, "start": 1651937549981, "stop": 1651937549981}], "start": 1651937549981, "stop": 1651937549981, "uuid": "8e13aac9-24fe-4cac-aa8b-f90328e3a62d", "historyId": "77e5cf12f32516bfe2a47f3219a213e4", "testCaseId": "3597cb11561d90f4dd644bf60f5c7512", "fullName": "test_5.Test#test_11", "labels": [{"name": "severity", "value": "critical"}, {"name": "story", "value": "登录"}, {"name": "suite", "value": "test_5"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "11812-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_5"}]}